name: C/C++ CI

on: [push, pull_request]

jobs:
  build-mac-default:
  # checking pure lib source distribution with plain configure & make
    runs-on: macos-10.12
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
